### ISSUE TITLE
Can't generate completions for Skyrim SE, error in threading.py

### ISSUE THREAD

**Issue by Verteiron** [Kapiainen/SublimePapyrus#29]
When attempting to generate completions for Skyrim SE, it fails to complete with the following console error: 
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "Plugin in C:\Users\Verteiron\AppData\Roaming\Sublime Text 3\Installed Packages\SublimePapyrus - Skyrim.sublime-package", line 62, in generate_completions
  File "./python3.3/encodings/cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 557: character maps to <undefined>
```
I always get 288 completion files, and the last one is always "SublimePapyrus - Skyrim - CWFortSiegeBarricadeScript". 

Edit: I get the same thing now when trying to generate completions for vanilla Skyrim, too. This started after a clean install of Windows 10, Sublime 3, and the latest SublimePapyrus.

**Comment by Kapiainen** [comment]
I tested and got the same error on my Windows 7 machine. The root of the problem seems to be that Python defaults to opening files with the default encoding of the OS' locale, which in this case is Windows-1252 (or CP-1252). So this problem also affects the linter and anything else trying to open and read files. The script that triggered the error is _CWFortSiegeCapitalPlayerScript_. The script can successfully be read provided that one specifies that UTF-8 encoding should be used.

This problem had gone unnoticed when testing during development of this command as a result of having all of my script sources in separate folders (vanilla scripts, SKSE, SkyUI SDK, etc.). I most likely only ran the command on the smaller collections of scripts. To be honest I had not expected anyone to generate completions for all 10000 scripts found in Skyrim (14000 if you include DLCs).

Is there a specific reason behind choosing to not use the dynamic completion system and instead opt to generate static completions? Was it a result of poorly worded documentation on my part that lead you to believe that running that command was necessary when it in fact was not? Was it simply a matter of preference? The static completions are a plan B kind of thing when there is an issue with running the linter and dynamic completion systems in the background while editing scripts (e.g. running it on a low-power device).

**Comment by Kapiainen** [comment]
A new branch called [encoding-fix](https://github.com/Kapiainen/SublimePapyrus/tree/encoding-fix) has been created to address the issue. Initial testing looks promising on my setup. I'll try to poke around a bit more before I merge the branch into master and release a new version.

**Comment by Verteiron** [comment]
Well, right after the install and for several launches of ST3 afterward, the linter was working but auto-completion was not working at all. It had been a long time since I'd last installed SP, so I thought maybe I'd generated the completions before and just forgotten to do it this time. 

I confess to not re-reading the documentation regarding the completion before seeing and trying the "generate completions" option; please don't hit me too hard :/ 

For reasons unknown, as I post this the autocomplete is now working. Nothing changed that I'm aware of, so I'm not sure why it was broken or why it suddenly started working and I realize that's not terribly helpful. I'm guessing this was probably user error, likely due to my being insufficiently patient.

**Comment by Kapiainen** [comment]
I'm glad to hear the dynamic auto-completion is working again for you. Don't worry about it. To be honest I think the readme could use with a bit more clarification anyway.

I'll close this issue once the new version with the fix is released, which I hope will take place before the end of this week. If you notice anything else, then please let me know about it.

**Comment by Kapiainen** [comment]
[Version 2.6.2 has been released.](https://github.com/Kapiainen/SublimePapyrus/releases/tag/2.6.2)
