### ISSUE TITLE
New linter crash

### ISSUE THREAD

**Issue by jimkaiseriv** [Kapiainen/SublimePapyrus#36]
I'm really not sure what caused this one. I didn't notice the crash for a little while, and I can't say exactly what preceded it. Hopefully the console error is useful to you, though. 

Exception in thread Thread-3490:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\threading.py", line 736, in run
  File ".\Plugin.py", line 413, in Linter
  File "C:\Users\Kaisers\AppData\Roaming\Sublime Text 2\Packages\SublimePapyrus - Skyrim\Linter.py", line 530, in Process
    if self.Statement() >= 0:
  File "C:\Users\Kaisers\AppData\Roaming\Sublime Text 2\Packages\SublimePapyrus - Skyrim\Linter.py", line 780, in Statement
    elif self.token.type == self.KW_STATE or (self.token.type == self.KW_AUTO and self.Peek().type == self.KW_STATE):
AttributeError: 'NoneType' object has no attribute 'type'

**Comment by Kapiainen** [comment]
I think I know what is happening. I'll have a fix up as soon as I can.

**Comment by Kapiainen** [comment]
[Version 2.6.10](https://github.com/Kapiainen/SublimePapyrus/releases/tag/2.6.10) fixes the issue. The issue was that just typing 'auto' meant that the linter had to peek one token forward, but the peek function returned None since 'auto' was the only thing on the line. All instances of calling the peek function, except for this particular one, checked the return value before trying to use it.

**Comment by jimkaiseriv** [comment]
I'm amazed by your quick response! Your explanation fits what I experienced, because I had defined an auto state not long before I noticed the crash. 

Thanks!

**Comment by Kapiainen** [comment]
No problem, would have been tricky figuring it out without the stack trace.
